// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/exercises/data/repositories/exercise_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/networking/common/api_result.dart' as _i4;
import 'package:fitness_app/features/exercises/data/data_sources/contract/exercise_data_sources.dart'
    as _i2;
import 'package:fitness_app/features/exercises/domain/entities/exercises_entity.dart'
    as _i5;
import 'package:fitness_app/features/exercises/domain/entities/levels_prime_over_muscle_entity.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExerciseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseDataSource extends _i1.Mock
    implements _i2.ExerciseDataSource {
  MockExerciseDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i5.ExercisesEntity>> getExercises(
    String? primeMoverMuscleId,
    String? difficultyLevelId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [
            primeMoverMuscleId,
            difficultyLevelId,
          ],
        ),
        returnValue: _i3.Future<_i4.DataResult<_i5.ExercisesEntity>>.value(
            _i6.dummyValue<_i4.DataResult<_i5.ExercisesEntity>>(
          this,
          Invocation.method(
            #getExercises,
            [
              primeMoverMuscleId,
              difficultyLevelId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i5.ExercisesEntity>>);

  @override
  _i3.Future<_i4.DataResult<_i7.LevelsPrimeMoverMuscleEntity>> getLevels(
          String? primeMoverMuscleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLevels,
          [primeMoverMuscleId],
        ),
        returnValue: _i3
            .Future<_i4.DataResult<_i7.LevelsPrimeMoverMuscleEntity>>.value(
            _i6.dummyValue<_i4.DataResult<_i7.LevelsPrimeMoverMuscleEntity>>(
          this,
          Invocation.method(
            #getLevels,
            [primeMoverMuscleId],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i7.LevelsPrimeMoverMuscleEntity>>);
}
