// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/meals/domain/use_cases/get_meal_by_id_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/networking/common/api_result.dart' as _i4;
import 'package:fitness_app/features/meals/domain/entities/meal_details_entity.dart'
    as _i8;
import 'package:fitness_app/features/meals/domain/entities/meal_entity.dart'
    as _i7;
import 'package:fitness_app/features/meals/domain/entities/meals_category_entity.dart'
    as _i5;
import 'package:fitness_app/features/meals/domain/repositories/meals_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MealsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsRepository extends _i1.Mock implements _i2.MealsRepository {
  MockMealsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<List<_i5.MealsCategoryEntity>>>
      getMealsCategories() => (super.noSuchMethod(
            Invocation.method(
              #getMealsCategories,
              [],
            ),
            returnValue: _i3
                .Future<_i4.DataResult<List<_i5.MealsCategoryEntity>>>.value(
                _i6.dummyValue<_i4.DataResult<List<_i5.MealsCategoryEntity>>>(
              this,
              Invocation.method(
                #getMealsCategories,
                [],
              ),
            )),
          ) as _i3.Future<_i4.DataResult<List<_i5.MealsCategoryEntity>>>);

  @override
  _i3.Future<_i4.DataResult<List<_i7.MealEntity>>> getMealsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsByCategory,
          [category],
        ),
        returnValue: _i3.Future<_i4.DataResult<List<_i7.MealEntity>>>.value(
            _i6.dummyValue<_i4.DataResult<List<_i7.MealEntity>>>(
          this,
          Invocation.method(
            #getMealsByCategory,
            [category],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<List<_i7.MealEntity>>>);

  @override
  _i3.Future<_i4.DataResult<_i8.MealDetailsEntity>> getMealById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealById,
          [id],
        ),
        returnValue: _i3.Future<_i4.DataResult<_i8.MealDetailsEntity>>.value(
            _i6.dummyValue<_i4.DataResult<_i8.MealDetailsEntity>>(
          this,
          Invocation.method(
            #getMealById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i8.MealDetailsEntity>>);
}
