// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/workouts/presentation/view_model/workouts_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/networking/common/api_result.dart' as _i4;
import 'package:fitness_app/features/workouts/domain/entities/response/get_all_workouts_by_id_entity.dart'
    as _i8;
import 'package:fitness_app/features/workouts/domain/entities/response/get_all_workouts_entity.dart'
    as _i5;
import 'package:fitness_app/features/workouts/domain/entities/response/muscles_by_muscle_group_id_entity.dart'
    as _i9;
import 'package:fitness_app/features/workouts/domain/use_cases/get_workout_by_id.dart'
    as _i7;
import 'package:fitness_app/features/workouts/domain/use_cases/workouts_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutsUseCase extends _i1.Mock implements _i2.WorkoutsUseCase {
  MockWorkoutsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i5.AllMusclesResponseEntity>> getAllWorkouts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWorkouts,
          [],
        ),
        returnValue:
            _i3.Future<_i4.DataResult<_i5.AllMusclesResponseEntity>>.value(
                _i6.dummyValue<_i4.DataResult<_i5.AllMusclesResponseEntity>>(
          this,
          Invocation.method(
            #getAllWorkouts,
            [],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i5.AllMusclesResponseEntity>>);
}

/// A class which mocks [GetWorkoutsByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWorkoutsByIdUseCase extends _i1.Mock
    implements _i7.GetWorkoutsByIdUseCase {
  MockGetWorkoutsByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i8.MusclesByIdResponseEntity>> getWorkoutById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutById,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.DataResult<_i8.MusclesByIdResponseEntity>>.value(
                _i6.dummyValue<_i4.DataResult<_i8.MusclesByIdResponseEntity>>(
          this,
          Invocation.method(
            #getWorkoutById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i8.MusclesByIdResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<List<_i9.MusclesByMuscleGroupIdEntity>>> call(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<
                _i4.DataResult<List<_i9.MusclesByMuscleGroupIdEntity>>>.value(
            _i6.dummyValue<
                _i4.DataResult<List<_i9.MusclesByMuscleGroupIdEntity>>>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<List<_i9.MusclesByMuscleGroupIdEntity>>>);
}
