// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/meals/data/data_sources/contracts/meals_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:fitness_app/core/networking/api/meals_api_manager/meals_api_manager.dart'
    as _i5;
import 'package:fitness_app/features/meals/data/models/meals_by_category_response_dto.dart'
    as _i3;
import 'package:fitness_app/features/meals/data/models/meals_categories_response_dto.dart'
    as _i2;
import 'package:fitness_app/features/meals/data/models/meals_details_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealsCategoriesResponseDto_0 extends _i1.SmartFake
    implements _i2.MealsCategoriesResponseDto {
  _FakeMealsCategoriesResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMealsByCategoryResponseDto_1 extends _i1.SmartFake
    implements _i3.MealsByCategoryResponseDto {
  _FakeMealsByCategoryResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMealsDetailsResponseDto_2 extends _i1.SmartFake
    implements _i4.MealsDetailsResponseDto {
  _FakeMealsDetailsResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MealsApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealsApiManager extends _i1.Mock implements _i5.MealsApiManager {
  MockMealsApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.MealsCategoriesResponseDto> getMealsCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsCategories,
          [],
        ),
        returnValue: _i6.Future<_i2.MealsCategoriesResponseDto>.value(
            _FakeMealsCategoriesResponseDto_0(
          this,
          Invocation.method(
            #getMealsCategories,
            [],
          ),
        )),
      ) as _i6.Future<_i2.MealsCategoriesResponseDto>);

  @override
  _i6.Future<_i3.MealsByCategoryResponseDto> getMealsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsByCategory,
          [category],
        ),
        returnValue: _i6.Future<_i3.MealsByCategoryResponseDto>.value(
            _FakeMealsByCategoryResponseDto_1(
          this,
          Invocation.method(
            #getMealsByCategory,
            [category],
          ),
        )),
      ) as _i6.Future<_i3.MealsByCategoryResponseDto>);

  @override
  _i6.Future<_i4.MealsDetailsResponseDto> getMealById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealById,
          [id],
        ),
        returnValue: _i6.Future<_i4.MealsDetailsResponseDto>.value(
            _FakeMealsDetailsResponseDto_2(
          this,
          Invocation.method(
            #getMealById,
            [id],
          ),
        )),
      ) as _i6.Future<_i4.MealsDetailsResponseDto>);
}
