// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/auth/domain/use_case/login_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/networking/common/api_result.dart' as _i4;
import 'package:fitness_app/features/auth/domain/contracts/auth_repo.dart'
    as _i2;
import 'package:fitness_app/features/auth/domain/entities/request/forget_password_request_entity.dart'
    as _i6;
import 'package:fitness_app/features/auth/domain/entities/request/login_request_entity.dart'
    as _i12;
import 'package:fitness_app/features/auth/domain/entities/request/reset_password_request_entity.dart'
    as _i10;
import 'package:fitness_app/features/auth/domain/entities/request/signup_request_entity.dart'
    as _i14;
import 'package:fitness_app/features/auth/domain/entities/request/verify_otp_request_enity.dart'
    as _i8;
import 'package:fitness_app/features/auth/domain/entities/response/forget_password_response_entity.dart'
    as _i5;
import 'package:fitness_app/features/auth/domain/entities/response/login_response_entity.dart'
    as _i11;
import 'package:fitness_app/features/auth/domain/entities/response/reset_password_response_entity.dart'
    as _i9;
import 'package:fitness_app/features/auth/domain/entities/response/sign_up_response_entity.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i5.ForgetPasswordResponseEntity>> forgetPassword(
          _i6.ForgetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue: _i3
            .Future<_i4.DataResult<_i5.ForgetPasswordResponseEntity>>.value(
            _i7.dummyValue<_i4.DataResult<_i5.ForgetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i5.ForgetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<void>> verifyOtp(
          _i8.VerifyOtpRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [request],
        ),
        returnValue: _i3.Future<_i4.DataResult<void>>.value(
            _i7.dummyValue<_i4.DataResult<void>>(
          this,
          Invocation.method(
            #verifyOtp,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<void>>);

  @override
  _i3.Future<_i4.DataResult<_i9.ResetPasswordResponseEntity>> resetPassword(
          _i10.ResetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.DataResult<_i9.ResetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.DataResult<_i9.ResetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i9.ResetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<_i11.LoginResponseEntity>> login(
          _i12.LoginRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i3.Future<_i4.DataResult<_i11.LoginResponseEntity>>.value(
            _i7.dummyValue<_i4.DataResult<_i11.LoginResponseEntity>>(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i11.LoginResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<_i13.SignUpResponseEntity>> signUp(
          {required _i14.SignUpRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {#request: request},
        ),
        returnValue:
            _i3.Future<_i4.DataResult<_i13.SignUpResponseEntity>>.value(
                _i7.dummyValue<_i4.DataResult<_i13.SignUpResponseEntity>>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#request: request},
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i13.SignUpResponseEntity>>);
}
