// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/meals/presentation/viewModel/meals_view_model_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/core/networking/common/api_result.dart' as _i5;
import 'package:fitness_app/features/meals/domain/entities/meal_details_entity.dart'
    as _i11;
import 'package:fitness_app/features/meals/domain/entities/meal_entity.dart'
    as _i9;
import 'package:fitness_app/features/meals/domain/entities/meals_category_entity.dart'
    as _i6;
import 'package:fitness_app/features/meals/domain/repositories/meals_repository.dart'
    as _i2;
import 'package:fitness_app/features/meals/domain/use_cases/get_meal_by_id_case.dart'
    as _i10;
import 'package:fitness_app/features/meals/domain/use_cases/get_meals_by_category_case.dart'
    as _i8;
import 'package:fitness_app/features/meals/domain/use_cases/get_meals_categories_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealsRepository_0 extends _i1.SmartFake
    implements _i2.MealsRepository {
  _FakeMealsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMealsCategoriesCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsCategoriesCase extends _i1.Mock
    implements _i3.GetMealsCategoriesCase {
  MockGetMealsCategoriesCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMealsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MealsRepository);

  @override
  _i4.Future<_i5.DataResult<List<_i6.MealsCategoryEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i5.DataResult<List<_i6.MealsCategoryEntity>>>.value(
                _i7.dummyValue<_i5.DataResult<List<_i6.MealsCategoryEntity>>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<List<_i6.MealsCategoryEntity>>>);
}

/// A class which mocks [GetMealsByCategoryCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsByCategoryCase extends _i1.Mock
    implements _i8.GetMealsByCategoryCase {
  MockGetMealsByCategoryCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMealsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MealsRepository);

  @override
  _i4.Future<_i5.DataResult<List<_i9.MealEntity>>> call(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [category],
        ),
        returnValue: _i4.Future<_i5.DataResult<List<_i9.MealEntity>>>.value(
            _i7.dummyValue<_i5.DataResult<List<_i9.MealEntity>>>(
          this,
          Invocation.method(
            #call,
            [category],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<List<_i9.MealEntity>>>);
}

/// A class which mocks [GetMealByIdCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealByIdCase extends _i1.Mock implements _i10.GetMealByIdCase {
  MockGetMealByIdCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMealsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MealsRepository);

  @override
  _i4.Future<_i5.DataResult<_i11.MealDetailsEntity>> call(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i4.Future<_i5.DataResult<_i11.MealDetailsEntity>>.value(
            _i7.dummyValue<_i5.DataResult<_i11.MealDetailsEntity>>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<_i11.MealDetailsEntity>>);
}
