// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/workouts/data/data_sources/online_data_sources/impl/get_all_workouts_online_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:io' as _i20;

import 'package:fitness_app/core/networking/api/api_manager.dart' as _i13;
import 'package:fitness_app/features/auth/data/models/request/forget_password_request_dto.dart'
    as _i15;
import 'package:fitness_app/features/auth/data/models/request/login_request_dto.dart'
    as _i16;
import 'package:fitness_app/features/auth/data/models/request/reset_password_request_dto.dart'
    as _i19;
import 'package:fitness_app/features/auth/data/models/request/signup_request_dto.dart'
    as _i17;
import 'package:fitness_app/features/auth/data/models/request/verify_otp_request_dto.dart'
    as _i18;
import 'package:fitness_app/features/auth/data/models/response/forget_response_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/data/models/response/login_response_dto.dart'
    as _i3;
import 'package:fitness_app/features/auth/data/models/response/reset_password_response_dto.dart'
    as _i5;
import 'package:fitness_app/features/auth/data/models/response/signup_response_dto.dart'
    as _i4;
import 'package:fitness_app/features/home/data/models/response/get_random_exercises_response_dto.dart'
    as _i12;
import 'package:fitness_app/features/home/data/models/response/get_random_muscles_response_dto.dart'
    as _i11;
import 'package:fitness_app/features/profile/data/models/response/edit_profile_response_dto.dart'
    as _i9;
import 'package:fitness_app/features/profile/data/models/response/profile_response_model.dart'
    as _i6;
import 'package:fitness_app/features/profile/data/models/response/upload_photo_response_dto.dart'
    as _i10;
import 'package:fitness_app/features/workouts/data/models/response/get_all_workout_by_id_dto.dart'
    as _i8;
import 'package:fitness_app/features/workouts/data/models/response/workouts_response_dto.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponseDto_1 extends _i1.SmartFake
    implements _i3.LoginResponseDto {
  _FakeLoginResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseDto_2 extends _i1.SmartFake
    implements _i4.SignUpResponseDto {
  _FakeSignUpResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResponseDto_4 extends _i1.SmartFake
    implements _i6.ProfileResponseDto {
  _FakeProfileResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutsResponseDto_5 extends _i1.SmartFake
    implements _i7.WorkoutsResponseDto {
  _FakeWorkoutsResponseDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllWorkoutsByIdDto_6 extends _i1.SmartFake
    implements _i8.GetAllWorkoutsByIdDto {
  _FakeGetAllWorkoutsByIdDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseDto_7 extends _i1.SmartFake
    implements _i9.EditProfileResponseDto {
  _FakeEditProfileResponseDto_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponseDto_8 extends _i1.SmartFake
    implements _i10.UploadPhotoResponseDto {
  _FakeUploadPhotoResponseDto_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRandomMusclesResponseDto_9 extends _i1.SmartFake
    implements _i11.GetRandomMusclesResponseDto {
  _FakeGetRandomMusclesResponseDto_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRandomExercisesResponseDto_10 extends _i1.SmartFake
    implements _i12.GetRandomExercisesResponseDto {
  _FakeGetRandomExercisesResponseDto_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i13.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i2.ForgetPasswordResponseDto> forgetPassword(
          _i15.ForgetPasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue: _i14.Future<_i2.ForgetPasswordResponseDto>.value(
            _FakeForgetPasswordResponseDto_0(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i14.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i14.Future<_i3.LoginResponseDto> login(_i16.LoginRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i14.Future<_i3.LoginResponseDto>.value(_FakeLoginResponseDto_1(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i14.Future<_i3.LoginResponseDto>);

  @override
  _i14.Future<_i4.SignUpResponseDto> signup(_i17.SignUpRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [request],
        ),
        returnValue:
            _i14.Future<_i4.SignUpResponseDto>.value(_FakeSignUpResponseDto_2(
          this,
          Invocation.method(
            #signup,
            [request],
          ),
        )),
      ) as _i14.Future<_i4.SignUpResponseDto>);

  @override
  _i14.Future<dynamic> verifyOtp(_i18.VerifyOtpRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [request],
        ),
        returnValue: _i14.Future<dynamic>.value(),
      ) as _i14.Future<dynamic>);

  @override
  _i14.Future<_i5.ResetPasswordResponseDto> resetPassword(
          _i19.ResetPasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i14.Future<_i5.ResetPasswordResponseDto>.value(
            _FakeResetPasswordResponseDto_3(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i14.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i14.Future<_i6.ProfileResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoggedUserData,
          [],
        ),
        returnValue:
            _i14.Future<_i6.ProfileResponseDto>.value(_FakeProfileResponseDto_4(
          this,
          Invocation.method(
            #getLoggedUserData,
            [],
          ),
        )),
      ) as _i14.Future<_i6.ProfileResponseDto>);

  @override
  _i14.Future<_i7.WorkoutsResponseDto> getAllWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorkouts,
          [],
        ),
        returnValue: _i14.Future<_i7.WorkoutsResponseDto>.value(
            _FakeWorkoutsResponseDto_5(
          this,
          Invocation.method(
            #getAllWorkouts,
            [],
          ),
        )),
      ) as _i14.Future<_i7.WorkoutsResponseDto>);

  @override
  _i14.Future<_i8.GetAllWorkoutsByIdDto> getWorkoutsById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutsById,
          [id],
        ),
        returnValue: _i14.Future<_i8.GetAllWorkoutsByIdDto>.value(
            _FakeGetAllWorkoutsByIdDto_6(
          this,
          Invocation.method(
            #getWorkoutsById,
            [id],
          ),
        )),
      ) as _i14.Future<_i8.GetAllWorkoutsByIdDto>);

  @override
  _i14.Future<_i9.EditProfileResponseDto> editProfile(
          Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [profileData],
        ),
        returnValue: _i14.Future<_i9.EditProfileResponseDto>.value(
            _FakeEditProfileResponseDto_7(
          this,
          Invocation.method(
            #editProfile,
            [profileData],
          ),
        )),
      ) as _i14.Future<_i9.EditProfileResponseDto>);

  @override
  _i14.Future<_i10.UploadPhotoResponseDto> uploadPhoto(_i20.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i14.Future<_i10.UploadPhotoResponseDto>.value(
            _FakeUploadPhotoResponseDto_8(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i14.Future<_i10.UploadPhotoResponseDto>);

  @override
  _i14.Future<_i11.GetRandomMusclesResponseDto> getRandomMuscles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomMuscles,
          [],
        ),
        returnValue: _i14.Future<_i11.GetRandomMusclesResponseDto>.value(
            _FakeGetRandomMusclesResponseDto_9(
          this,
          Invocation.method(
            #getRandomMuscles,
            [],
          ),
        )),
      ) as _i14.Future<_i11.GetRandomMusclesResponseDto>);

  @override
  _i14.Future<dynamic> getMealsCategories() => (super.noSuchMethod(
        Invocation.method(
          #getMealsCategories,
          [],
        ),
        returnValue: _i14.Future<dynamic>.value(),
      ) as _i14.Future<dynamic>);

  @override
  _i14.Future<_i12.GetRandomExercisesResponseDto> getRandomExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomExercises,
          [],
        ),
        returnValue: _i14.Future<_i12.GetRandomExercisesResponseDto>.value(
            _FakeGetRandomExercisesResponseDto_10(
          this,
          Invocation.method(
            #getRandomExercises,
            [],
          ),
        )),
      ) as _i14.Future<_i12.GetRandomExercisesResponseDto>);
}
