// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fitness_app/features/smart_coach_chat/data/models/offline/message_hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatHiveAdapter());
    registerAdapter(MessageHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatHiveAdapter());
    registerAdapter(MessageHiveAdapter());
  }
}
