// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/auth/data/contracts/auth_online_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:io' as _i18;

import 'package:fitness_app/core/networking/api/api_manager.dart' as _i11;
import 'package:fitness_app/features/auth/data/models/request/forget_password_request_dto.dart'
    as _i13;
import 'package:fitness_app/features/auth/data/models/request/login_request_dto.dart'
    as _i14;
import 'package:fitness_app/features/auth/data/models/request/reset_password_request_dto.dart'
    as _i17;
import 'package:fitness_app/features/auth/data/models/request/signup_request_dto.dart'
    as _i15;
import 'package:fitness_app/features/auth/data/models/request/verify_otp_request_dto.dart'
    as _i16;
import 'package:fitness_app/features/auth/data/models/response/forget_response_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/data/models/response/login_response_dto.dart'
    as _i3;
import 'package:fitness_app/features/auth/data/models/response/reset_password_response_dto.dart'
    as _i5;
import 'package:fitness_app/features/auth/data/models/response/signup_response_dto.dart'
    as _i4;
import 'package:fitness_app/features/home/data/models/response/get_meals_categories_response_dto.dart'
    as _i10;
import 'package:fitness_app/features/home/data/models/response/get_random_muscles_response_dto.dart'
    as _i9;
import 'package:fitness_app/features/profile/data/models/response/edit_profile_response_dto.dart'
    as _i7;
import 'package:fitness_app/features/profile/data/models/response/profile_response_model.dart'
    as _i6;
import 'package:fitness_app/features/profile/data/models/response/upload_photo_response_dto.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponseDto_1 extends _i1.SmartFake
    implements _i3.LoginResponseDto {
  _FakeLoginResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseDto_2 extends _i1.SmartFake
    implements _i4.SignUpResponseDto {
  _FakeSignUpResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResponseDto_4 extends _i1.SmartFake
    implements _i6.ProfileResponseDto {
  _FakeProfileResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseDto_5 extends _i1.SmartFake
    implements _i7.EditProfileResponseDto {
  _FakeEditProfileResponseDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponseDto_6 extends _i1.SmartFake
    implements _i8.UploadPhotoResponseDto {
  _FakeUploadPhotoResponseDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRandomMusclesResponseDto_7 extends _i1.SmartFake
    implements _i9.GetRandomMusclesResponseDto {
  _FakeGetRandomMusclesResponseDto_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMealsCategoriesResponseDto_8 extends _i1.SmartFake
    implements _i10.GetMealsCategoriesResponseDto {
  _FakeGetMealsCategoriesResponseDto_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i11.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.ForgetPasswordResponseDto> forgetPassword(
          _i13.ForgetPasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue: _i12.Future<_i2.ForgetPasswordResponseDto>.value(
            _FakeForgetPasswordResponseDto_0(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i12.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i12.Future<_i3.LoginResponseDto> login(_i14.LoginRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i12.Future<_i3.LoginResponseDto>.value(_FakeLoginResponseDto_1(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i12.Future<_i3.LoginResponseDto>);

  @override
  _i12.Future<_i4.SignUpResponseDto> signup(_i15.SignUpRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [request],
        ),
        returnValue:
            _i12.Future<_i4.SignUpResponseDto>.value(_FakeSignUpResponseDto_2(
          this,
          Invocation.method(
            #signup,
            [request],
          ),
        )),
      ) as _i12.Future<_i4.SignUpResponseDto>);

  @override
  _i12.Future<dynamic> verifyOtp(_i16.VerifyOtpRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [request],
        ),
        returnValue: _i12.Future<dynamic>.value(),
      ) as _i12.Future<dynamic>);

  @override
  _i12.Future<_i5.ResetPasswordResponseDto> resetPassword(
          _i17.ResetPasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i12.Future<_i5.ResetPasswordResponseDto>.value(
            _FakeResetPasswordResponseDto_3(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i12.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i12.Future<_i6.ProfileResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoggedUserData,
          [],
        ),
        returnValue:
            _i12.Future<_i6.ProfileResponseDto>.value(_FakeProfileResponseDto_4(
          this,
          Invocation.method(
            #getLoggedUserData,
            [],
          ),
        )),
      ) as _i12.Future<_i6.ProfileResponseDto>);

  @override
  _i12.Future<_i7.EditProfileResponseDto> editProfile(
          Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [profileData],
        ),
        returnValue: _i12.Future<_i7.EditProfileResponseDto>.value(
            _FakeEditProfileResponseDto_5(
          this,
          Invocation.method(
            #editProfile,
            [profileData],
          ),
        )),
      ) as _i12.Future<_i7.EditProfileResponseDto>);

  @override
  _i12.Future<_i8.UploadPhotoResponseDto> uploadPhoto(_i18.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i12.Future<_i8.UploadPhotoResponseDto>.value(
            _FakeUploadPhotoResponseDto_6(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i12.Future<_i8.UploadPhotoResponseDto>);

  @override
  _i12.Future<_i9.GetRandomMusclesResponseDto> getRandomMuscles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomMuscles,
          [],
        ),
        returnValue: _i12.Future<_i9.GetRandomMusclesResponseDto>.value(
            _FakeGetRandomMusclesResponseDto_7(
          this,
          Invocation.method(
            #getRandomMuscles,
            [],
          ),
        )),
      ) as _i12.Future<_i9.GetRandomMusclesResponseDto>);

  @override
  _i12.Future<_i10.GetMealsCategoriesResponseDto> getMealsCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsCategories,
          [],
        ),
        returnValue: _i12.Future<_i10.GetMealsCategoriesResponseDto>.value(
            _FakeGetMealsCategoriesResponseDto_8(
          this,
          Invocation.method(
            #getMealsCategories,
            [],
          ),
        )),
      ) as _i12.Future<_i10.GetMealsCategoriesResponseDto>);
}
