// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/features/auth/data/contracts/auth_online_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:fitness_app/core/networking/api/api_manager.dart' as _i8;
import 'package:fitness_app/features/auth/data/models/request/forget_password_request_dto.dart'
    as _i10;
import 'package:fitness_app/features/auth/data/models/request/login_request_dto.dart'
    as _i11;
import 'package:fitness_app/features/auth/data/models/request/reset_password_request_dto.dart'
    as _i14;
import 'package:fitness_app/features/auth/data/models/request/signup_request_dto.dart'
    as _i12;
import 'package:fitness_app/features/auth/data/models/request/verify_otp_request_dto.dart'
    as _i13;
import 'package:fitness_app/features/auth/data/models/response/forget_response_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/data/models/response/login_response_dto.dart'
    as _i3;
import 'package:fitness_app/features/auth/data/models/response/reset_password_response_dto.dart'
    as _i5;
import 'package:fitness_app/features/auth/data/models/response/signup_response_dto.dart'
    as _i4;
import 'package:fitness_app/features/profile/data/models/response/edit_profile_response_dto.dart'
    as _i7;
import 'package:fitness_app/features/profile/data/models/response/profile_response_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseDto_1 extends _i1.SmartFake
    implements _i3.LoginResponseDto {
  _FakeLoginResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignUpResponseDto_2 extends _i1.SmartFake
    implements _i4.SignUpResponseDto {
  _FakeSignUpResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponseDto_4 extends _i1.SmartFake
    implements _i6.ProfileResponseDto {
  _FakeProfileResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEditProfileResponseDto_5 extends _i1.SmartFake
    implements _i7.EditProfileResponseDto {
  _FakeEditProfileResponseDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i8.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.ForgetPasswordResponseDto> forgetPassword(
    _i10.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i9.Future<_i2.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_0(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i9.Future<_i2.ForgetPasswordResponseDto>);

  @override
  _i9.Future<_i3.LoginResponseDto> login(_i11.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i9.Future<_i3.LoginResponseDto>.value(
              _FakeLoginResponseDto_1(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i9.Future<_i3.LoginResponseDto>);

  @override
  _i9.Future<_i4.SignUpResponseDto> signup(_i12.SignUpRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [request]),
            returnValue: _i9.Future<_i4.SignUpResponseDto>.value(
              _FakeSignUpResponseDto_2(
                this,
                Invocation.method(#signup, [request]),
              ),
            ),
          )
          as _i9.Future<_i4.SignUpResponseDto>);

  @override
  _i9.Future<dynamic> verifyOtp(_i13.VerifyOtpRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue: _i9.Future<dynamic>.value(),
          )
          as _i9.Future<dynamic>);

  @override
  _i9.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i14.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i9.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i9.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i9.Future<_i6.ProfileResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserData, []),
            returnValue: _i9.Future<_i6.ProfileResponseDto>.value(
              _FakeProfileResponseDto_4(
                this,
                Invocation.method(#getLoggedUserData, []),
              ),
            ),
          )
          as _i9.Future<_i6.ProfileResponseDto>);

  @override
  _i9.Future<_i7.EditProfileResponseDto> editProfile(
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [profileData]),
            returnValue: _i9.Future<_i7.EditProfileResponseDto>.value(
              _FakeEditProfileResponseDto_5(
                this,
                Invocation.method(#editProfile, [profileData]),
              ),
            ),
          )
          as _i9.Future<_i7.EditProfileResponseDto>);
}
