name: Dart Linting

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-dart-tool-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache Dart tool
        uses: actions/cache@v3
        with:
          path: .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-dart-tool-

      - name: Create placeholder .env.firebase
        run: echo "FIREBASE_CONFIG_PLACEHOLDER=true" > .env.firebase

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart Fix
        run: dart fix --apply

      - name: Run Flutter analyzer
        run: flutter analyze

